[package]
name = "egui_sdl2_gl"
version = "0.1.9"
authors = ["Arjun Nair <arjunair@gmail.com>"]
edition = "2018"
description = "Backend for Egui to use with sdl2-rs and open gl"
homepage = "https://github.com/ArjunNair/egui_sdl2_gl"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ArjunNair/egui_sdl2_gl"
categories = ["gui", "graphics"]
keywords = ["sdl2", "opengl", "egui", "gui", "gamedev"]
include = [ "**/*.rs", "Cargo.toml"]

[dependencies]
sdl2 = "0.34.3"
gl = "0.14.0"
clipboard = "0.5"
egui = "0.9.0"